# Generated by Django 2.2.7 on 2020-09-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_format', models.FileField(help_text='upload a file', upload_to='media/')),
                ('file_name', models.CharField(help_text='add a file description', max_length=100)),
            ],
        ),
    ]
