# Generated by Django 2.2.7 on 2020-09-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20200912_1116'),
        ('auth', '0011_update_proxy_permissions'),
        ('pixabay', '0002_auto_20200912_1114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
