# Generated by Django 2.2.7 on 2020-09-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixabay', '0003_auto_20200912_1116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
